## 1. Create 2 matrices. a of size 3x4, and b of size 5x4, and merged them into one single one of size 8x4

In [1]:
import numpy as np

In [3]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=np.array([[13,14,15,16],[17,18,19,20],[21,22,23,24],[25,26,27,28],[30,31,32,33]])

In [4]:
c=np.concatenate([a,b],axis=0)

In [6]:
print(f"The final results is a {c.shape} matrix :\n\n{c}")

The final results is a (8, 4) matrix :

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [30 31 32 33]]


## 2. Create a vector of size 10 and call it a. Now copy it into a new vector and call it b, but make the values in b shifted by one index to the right from the values in a. Use 0 to ensure the both have the same length. 

In [7]:
a=np.arange(10)
b=a[:-1]
print(f"The resultant vector 'b' is shifted by 1 index to right from a :{b}")

The resultant vector 'b' is shifted by 1 index to right from a :[0 1 2 3 4 5 6 7 8]


## 3. Create a matrix x, and a mask matrix m, add or multiply x with m (x operation m = new_x) sothat only the values below the diagonal appear in the new matrix (new_x).

In [9]:
x=np.array([[2,4,3],[6,5,3],[8,9,1]])

m=x>5
print(f"Masked Matrix from x:\n{x}")

new_x=x*m
print(f"\n The new matrix after required operation x*m:\n{new_x}")

Masked Matrix from x:
[[2 4 3]
 [6 5 3]
 [8 9 1]]

 The new matrix after required operation x*m:
[[0 0 0]
 [6 0 0]
 [8 9 0]]
