## PyTorch Basics

In [5]:
import torch
import numpy as np
import h5py

In [6]:
a = torch.ones(3)

print(a)

tensor([1., 1., 1.])


In [7]:
a[2] = 17.0

print(a)

tensor([ 1.,  1., 17.])


In [8]:
b = [4.0, 1.0, 5.0, 3.0, 2.0, 1.0]

b_tf = torch.tensor(b)

print(b_tf)

tensor([4., 1., 5., 3., 2., 1.])


In [9]:
c = [[4.0, 1.0],[5.0, 3.0],[2.0, 1.0]]

c_tf = torch.tensor(c)

print(c_tf)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


In [10]:
print(c_tf.shape)

torch.Size([3, 2])


In [11]:
d_tf = torch.zeros(3, 2)

print (d_tf)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [12]:
d_tf[0,1] = 17.0

print(d_tf)

tensor([[ 0., 17.],
        [ 0.,  0.],
        [ 0.,  0.]])


### This segment covers the Slicing of Data

In [16]:
sliced_d = d_tf[1:, :]

print(sliced_d)

tensor([[0., 0.],
        [0., 0.]])


In [18]:
sliced_d = d_tf[:, 1:]

print(sliced_d)

tensor([[17.],
        [ 0.],
        [ 0.]])


In [19]:
d_tf_dim = d_tf[..., None]

print(d_tf.shape)
print(d_tf_dim.shape)

torch.Size([3, 2])
torch.Size([3, 2, 1])


In [20]:
batch_tf = torch.randn(16, 3, 28, 28) ## images in this shape (batch_size, channels for RGB, rows, columns) 

print(batch_tf)
print(batch_tf.shape)

tensor([[[[ 1.5407e+00, -9.1570e-02,  8.8786e-01,  ..., -6.0524e-01,
            3.1040e-01, -9.8825e-01],
          [ 6.2795e-01, -1.2285e+00, -2.0119e+00,  ...,  1.4805e+00,
            1.2616e+00, -1.1108e-01],
          [ 7.5769e-01, -6.6713e-01, -1.6724e-01,  ..., -6.2256e-01,
           -5.0201e-01,  9.3097e-01],
          ...,
          [-3.9668e-01, -1.2090e+00, -1.4621e+00,  ..., -1.9162e-01,
            1.0335e+00,  1.0907e+00],
          [ 6.8548e-01, -2.5345e+00, -1.7308e+00,  ...,  1.5067e+00,
            4.8114e-01, -1.0334e-01],
          [ 1.2738e+00,  8.3547e-01,  3.3593e-01,  ...,  1.4106e+00,
           -1.4550e-01, -5.1973e-01]],

         [[ 1.6528e+00, -3.2643e-02, -2.5697e-01,  ..., -1.5227e+00,
            1.1209e+00,  1.0705e-01],
          [-1.7342e+00,  3.4337e-01, -1.0908e+00,  ..., -3.5787e-01,
            1.3690e+00, -1.0515e+00],
          [ 3.5349e-01, -2.9612e-01, -4.6115e-01,  ..., -1.2870e-01,
            2.2926e+00,  5.6333e-02],
          ...,
     

### Data Type For a Tensor

In [21]:
double_points = torch.ones(10, 2, dtype = torch.double)
short_points = torch.tensor([[1, 2],[3, 4]], dtype = torch.short)

print(double_points.shape)
print(short_points)
print(short_points.shape)
print(short_points.dtype)

torch.Size([10, 2])
tensor([[1, 2],
        [3, 4]], dtype=torch.int16)
torch.Size([2, 2])
torch.int16


### Torch/Numpy Interoperability

In [23]:
points = torch.ones(3, 4)

points_np = points.numpy()

print(points)
print(points_np)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
points_tf = torch.from_numpy(points_np)
print(points_tf)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [25]:
torch.save(points,'data/example_points.t')

In [26]:
points2 = torch.load('data/example_points.t')
print(points2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### Serializing with HDF5

In [28]:
f = h5py.File('data/points.hdf5', 'w')

dset = f.create_dataset('Coordinates', data = points.numpy())
f.close()

In [29]:
f = h5py.File('data/points.hdf5', 'r')

print(f)

<HDF5 file "points.hdf5" (mode r)>


In [33]:
dset = f['Coordinates']
dset = dset[:,:]

print(dset)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
dset_tr = torch.from_numpy(dset)

print(dset_tr) 

f.close()

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
