## Simple Neural Network

In [111]:
import torch
import numpy as np

import matplotlib.pyplot as plt

import torch.optim as optim
import torch.nn as nn

In [112]:
# Inputs
t_c = [0.5,  14.0, 15.0, 28.0, 11.0,  8.0,  3.0, -4.0,  6.0, 13.0, 21.0]

# Outputs
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]

t_c = torch.tensor(  t_c   )
t_u = torch.tensor(  t_u   )

print(t_u.shape)
print(t_c.shape)

t_c = t_c.unsqueeze(1)
t_u = t_u.unsqueeze(1)

print(t_u.shape)
print(t_c.shape)

# t_u = 0.1 * t_u (for normalizing)

torch.Size([11])
torch.Size([11])
torch.Size([11, 1])
torch.Size([11, 1])


## Splitting the Data

In [113]:
n_samples = t_u.shape[0]
n_samples

11

In [114]:
n_val = int(0.3 * n_samples)
n_val

3

In [115]:
shuffled_indeces = torch.randperm(n_samples)
shuffled_indeces

tensor([ 2,  7,  0, 10,  8,  1,  5,  3,  9,  4,  6])

In [116]:
train_indeces = shuffled_indeces[:-n_val]
val_indeces = shuffled_indeces[-n_val:]

print(train_indeces)
print(val_indeces)

tensor([ 2,  7,  0, 10,  8,  1,  5,  3])
tensor([9, 4, 6])


In [125]:
train_t_u = t_u[train_indeces]
train_t_c = t_c[train_indeces]

val_t_u = t_u[train_indeces]
val_t_c = t_c[train_indeces]

## Training Loop

In [126]:
def training_loop(n_epochs, optimizer, model, loss_fn, train_t_u, val_t_u, train_t_c, val_t_c):
    
    for epoch in range(1, n_epochs):
        
        train_t_p = model(train_t_u)
        train_loss = loss_fn(train_t_p, train_t_c)
        
        val_t_p = model(val_t_u)
        val_loss = loss_fn(val_t_p, val_t_c)
        
        optimizer.zero_grad()
        train_loss.backward()
        optimizer.step()
        
        
        if epoch % 500 == 0:
            print("Train Loss: ", train_loss.item())
            print("Val Loss: ", val_loss.item())


## Architecture (Neural Network)

In [127]:
def model_fn_linear():
    return nn.Linear(1, 1)

In [128]:
## MLP

def model_fn_nn_1hidden():
    
    seq_model = nn.Sequential(
        nn.Linear(1, 13),
        nn.Tanh(),
        
        nn.Linear(13, 1),
    
    )
    
    return seq_model

In [129]:
def model_deep_learning_3hidden():
    seq_model = nn.Sequential(
        nn.Linear(1, 20),
        nn.ReLU(),
        
        nn.Linear(20, 10),
        nn.Tanh(),
        
        nn.Linear(10, 5),
        nn.Tanh(),
        
        nn.Linear(5, 1)
    )
    
    return seq_model

## Function Calls

In [131]:
## model = model_fn_linear()

model = model_fn_nn_1hidden()

##model = model_deep_learning_3hidden()
optimizer = optim.Adam(model.parameters(), lr = 0.001)
loss_fn = nn.MSELoss()

## Call Training Loop

In [132]:
result = training_loop(
    
    n_epochs = 30000,
    optimizer = optimizer,
    model = model,
    loss_fn = loss_fn,
    train_t_u = train_t_u,
    val_t_u = val_t_u,
    train_t_c = train_t_c,
    val_t_c = val_t_c
)


Train Loss:  119.6680908203125
Val Loss:  119.6680908203125
Train Loss:  86.40985107421875
Val Loss:  86.40985107421875
Train Loss:  67.35377502441406
Val Loss:  67.35377502441406
Train Loss:  51.88848876953125
Val Loss:  51.88848876953125
Train Loss:  38.601951599121094
Val Loss:  38.601951599121094
Train Loss:  27.713743209838867
Val Loss:  27.713743209838867
Train Loss:  19.280574798583984
Val Loss:  19.280574798583984
Train Loss:  13.115633964538574
Val Loss:  13.115633964538574
Train Loss:  8.895417213439941
Val Loss:  8.895417213439941
Train Loss:  6.205022811889648
Val Loss:  6.205022811889648
Train Loss:  4.468473434448242
Val Loss:  4.468473434448242
Train Loss:  3.2044432163238525
Val Loss:  3.2044432163238525
Train Loss:  2.2880136966705322
Val Loss:  2.2880136966705322
Train Loss:  1.6461204290390015
Val Loss:  1.6461204290390015
Train Loss:  1.215924859046936
Val Loss:  1.215924859046936
Train Loss:  0.917737603187561
Val Loss:  0.917737603187561
Train Loss:  0.73911964893

In [133]:
## Celsius from Farenheit
## 100 c = 212 f

my_Temp = model(val_t_u)

print(my_Temp)

tensor([[14.9033],
        [-3.9993],
        [ 0.4629],
        [21.0066],
        [ 6.6166],
        [14.1322],
        [ 7.3805],
        [27.9986]], grad_fn=<AddmmBackward0>)


In [134]:
print(val_t_c)

tensor([[15.0000],
        [-4.0000],
        [ 0.5000],
        [21.0000],
        [ 6.0000],
        [14.0000],
        [ 8.0000],
        [28.0000]])
